name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build
        run: mvn -B -DskipTests=false clean package

      - name: Run tests
        run: mvn -B -q test

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: boardgame-catalog-jar
          path: target/*.jar
